version: '2.1'

networks:
  monitor-net:
    driver: bridge

volumes:
    volume_data: {}

services:

  webgenerator:
    image: webgenerator
    command: ./app.sh
    volumes:
    - volume_data:/tmp/
    links:
    - webserver
  
  webserver:
    image: nginx
    ports:
    - "8089:80"
    volumes:
    - volume_data:/usr/share/nginx/html/
